#!/bin/bash
#Author: Zach Reed
#Description:  Matrix Script
#Date: 4/22/2019
#--------------------------------------------

#-------------------------------------------
#Temporary Files Declarations  in /tmp
row_n=$(mktemp /tmp/row_n.XXXXXXXX)
col_n=$(mktemp /tmp/col_n.XXXXXXXX)

#-------------------------------------------
#Function:      Cleanup
#Description:    Removes temporary files
#-------------------------------------------

trap "rm -f $row_n $col_n" INT HUP TERM


#--------------------------------------------
#Dimensions Function
#Description:   prints out returns from n_row()
#               and n_col(), respectively.
dims(){
	read  c_line < $1
	col_n = 0;
        for i in $c_line
	do
		((col_n++))
	done < "$1"
	echo "Col:"
	echo " $col_n"
}

if [[ $1 == "dims" ]]
then
	if [[ $# == "1" ]]
	then
		echo "1 argument"

	elif [[ $# == "2" && -r "$2" ]]
	then
		echo "--------------"
        	while read -r line
       		do
               		echo "$line"
 	       	done < "$1"
		echo "--------------"
 		dims $2
	fi
fi

