#!/bin/bash
#------------------------------
#Author: Zach Reed
#Description:  Matrix Script
#Date: 9/27/2019
#------------------------------


#-----------------------
# Temporary Files
#-----------------------
m1="m1_$$"
m2="m2_$$"
m3="m3_$$"
m4="m4_$$"

trap "rm -f $m1 $m2 $m3 $m4; echo 'SIGINT received: Deleting temp files..'; exit 1" INT
#-----------------------
# Error Function Handler
#-----------------------
err() {
	echo "$@" >&2
}

#-----------------------
# Get Columns  Function
#-----------------------
cols() {
	read line<$1
	local col_n=0
	for i in $line
	do
		((++col_n))
	done
	echo "$col_n"
}

#-----------------------
# Get Rows Function
#-----------------------
rows() {
	local row_n=0
	while read -r line
	do
		((++row_n))
	done < "$1"
	echo "$row_n"	
}

#-----------------------
# dimension Function
#-----------------------

dims() {
	#cols $1 $m1
	local col_n=$(cols $m1)
	local row_n=$(rows $m1)
	echo "$row_n $col_n"
}

#-----------------------
# transpose Function
#-----------------------
transpose() {
	local col_n=$(cols $m1)
	local row_n=$(rows $m1)	

	for ((i=1 ; i<=$col_n ; i++))
	do 
		line=$(cat $m1 | cut -f $i -d$'\t' | tr "\n" "\t")
		line=${line%?}
		echo "$line"
	done	
}

#-----------------------
# mean Function
#-----------------------
mean() {
        local col_n=$(cols $m1)
        local row_n=$(rows $m1)
	local sum=0
	local mean=0

	for ((i=1 ; i<=$col_n ; i++))
	do
		line=$(cat $m1 | cut -f $i -d$'\t' | tr "\n" "\t")
		for j in $line
		do
			sum=$(($j + $sum))
		done
		mean=$((($sum+($row_n/2)*( ($sum>0)*2-1))/$row_n))
		if [[ $i == 1 ]]               
                then
                	printf "%d" $mean

                else
                	printf "\t%d" $mean
                fi

		mean=0
		sum=0
	done
	printf "\n"
}


#-----------------------
# Add Function
#-----------------------
add() {
	err "Add not implemented"
}


#-----------------------
# Main Function
#-----------------------

main() {
	#echo $1 ${@:2}

	if [[ $(type -t $1) == "function" ]]
	then
		if [[ $1 == "dims" || $1 == "mean" || $1 == "transpose" ]]
		then
			if [ "$#" = "1" ]
			then
    				cat > "$m1"

			elif [ "$#" = "2" ]
			then
    				m1=$2

			elif [ "$#" > 2 ]
			then 
				err "Invalid arguments: " $#
				exit 2
			fi
		
			$1
			exit 0

		else
			echo "handler for if not dims/mean"
		fi
	else
		err "Invalid function call: $1"
	fi
}

# "${@:2}" takes all args from > 1st arg 
main $1 "${@:2}"

